FROM php:8.1-fpm

WORKDIR /var/www

RUN apt-get update

RUN apt-get install -y libzip-dev
RUN apt-get install -y git
RUN apt-get install -y curl
RUN apt-get install -y libpng-dev
RUN apt-get install -y libonig-dev
RUN apt-get install -y libxml2-dev
RUN apt-get install -y zip
RUN apt-get install -y unzip
RUN apt-get install -y nano
RUN apt-get install -y mc
RUN apt-get install -y nodejs
RUN apt-get install -y npm

RUN pecl install -o -f redis
RUN rm -rf /tmp/pear
RUN docker-php-ext-enable redis

RUN docker-php-ext-install pdo pdo_mysql mysqli sockets gd zip

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
